version: "3"
services:
  master:
    container_name: master
    image: jenkinsci/jenkins:2.142-slim
    ports:
     - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    links:
      - slave01

  slave01:
    container_name: slave01
    image: jenkinsci/ssh-slave
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZz2ktojawxUgN54jq0gS8GgC5WlcHrUQcjTLtJwmOWJ1wMGtsypnK7wulUB/XVZttAP4bJzgK076O5fYhjRPxA1VxY4oXuhfg2SqUbeZx22JHD9nwXwT3PB1E8BysrBvLTI08ncjGcNVigCGMKeufbIF5pLJ6qWeOubVzS8Z16IA2mqzQnzvkyeRMPJVzqsOLO3x4NFAgupt6OCBzWw49tqFQbLvLz5hwaGMfILlldJEas0wIv0h6QyOqcQ44UEBE3hNmTehDg3jRciDqkj0z8aVNU+elL5hPC/NG8jU6cTc7uTKs1NANI7D9xXaJitzF2wVUvsZm2AanGGoY9o6l
